name: Auto merge dev2main

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FROM: develop
  TO: main

jobs:
  auto-merge-dev2stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{env.FROM}}
      - name: 【定期実行】Create Pull Request dev2stage
        id: create-pull-request
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo -e "> [!IMPORTANT]\n> plz use `create` merge" | gh pr create -B ${{env.TO}} -t "`TZ=Asia/Tokyo date "+%Y%m%d"`【定期実行】dev2stage" -F=-
        
