name: Auto merge dev2main

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FROM: develop
  TO: main

jobs:
  auto-merge-dev2stage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{env.FROM}}
      - name: Count Diff
        id: count-diff
        run: echo "count=$(git diff origin/${{env.FROM}}...origin/${{env.TO}} --name-only | wc -l)" >> $GITHUB_OUTPUT
      - name: 【定期実行】Create Pull Request dev2stage
        id: create-pull-request
        if: steps.count-diff.outputs.count > 0
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create -B ${{env.TO}} -t "`TZ=Asia/Tokyo date "+%Y%m%d"`【定期実行】dev2stage" -b ""
