name: 'CI'

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'develop'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{github.event.pull_request.title}}
          regex: '^(feat:|fix:|perf:)'
      - run: exit 1
        if: ${{steps.regex-match.outputs.match == ''}}
